package com.kfarms.reports;

import com.lowagie.text.*;
import com.lowagie.text.Font;
import com.lowagie.text.pdf.*;

import java.awt.*;
import java.io.ByteArrayOutputStream;
import java.lang.reflect.Field;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

public class PdfReportBuilder {

    private static final Color KFARMS_PURPLE = new Color(107, 70, 193); // 💜 Purple

    public static <T> byte[] buildReport(List<T> dataList, String title, List<String> headers) throws Exception {

        if (headers == null || headers.isEmpty()) {
            throw new IllegalArgumentException("Headers cannot be null or empty");
        }

        Document document = new Document(PageSize.A4.rotate());
        ByteArrayOutputStream out = new ByteArrayOutputStream();

        try {
            PdfWriter.getInstance(document, out);
            document.open();

            // Try to use system font if available; fallback to Helvetica safely
            BaseFont base;
            try {
                base = BaseFont.createFont("fonts/DejaVuSans.ttf", BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
            } catch (Exception e) {
                base = BaseFont.createFont(BaseFont.HELVETICA, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED);
            }

            Font titleFont = new Font(base, 18, Font.BOLD, KFARMS_PURPLE);
            Font headerFont = new Font(base, 12, Font.BOLD, Color.WHITE);
            Font cellFont = new Font(base, 11, Font.NORMAL, Color.BLACK);
            Font footerFont = new Font(base, 9, Font.ITALIC, Color.GRAY);

            // ✅ DEBUG LOGS
            System.out.println("📄 Building PDF report for: " + title);
            System.out.println("Headers: " + headers);
            System.out.println("Records: " + (dataList != null ? dataList.size() : 0));

            // ---------- TITLE ----------
            Paragraph titlePara = new Paragraph(title, titleFont);
            titlePara.setAlignment(Element.ALIGN_CENTER);
            titlePara.setSpacingAfter(20);
            document.add(titlePara);

            // ---------- TABLE ----------
            PdfPTable table = new PdfPTable(headers.size());
            table.setWidthPercentage(100);
            table.setSpacingBefore(10f);
            table.setSpacingAfter(10f);

            // ---------- HEADER ROW ----------
            for (String header : headers) {
                PdfPCell cell = new PdfPCell(new Phrase(header, headerFont));
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                cell.setBackgroundColor(KFARMS_PURPLE);
                cell.setPadding(6f);
                table.addCell(cell);
            }

            // ---------- DATA ROWS ----------
            if (dataList != null && !dataList.isEmpty()) {
                for (Object obj : dataList) {
                    Field[] fields = getAllFields(obj.getClass());
                    for (int i = 0; i < headers.size(); i++) {
                        PdfPCell cell;
                        try {
                            if (i < fields.length) {
                                fields[i].setAccessible(true);
                                Object value = fields[i].get(obj);
                                String text = (value != null) ? value.toString() : "-";
                                cell = new PdfPCell(new Phrase(text, cellFont));
                            } else {
                                cell = new PdfPCell(new Phrase("-", cellFont));
                            }
                        } catch (Exception ex) {
                            cell = new PdfPCell(new Phrase("ERR", cellFont));
                        }
                        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                        cell.setPadding(5f);
                        table.addCell(cell);
                    } 
                }
            } else {
                PdfPCell emptyCell = new PdfPCell(new Phrase("No records found", cellFont));
                emptyCell.setColspan(headers.size());
                emptyCell.setHorizontalAlignment(Element.ALIGN_CENTER);
                emptyCell.setPadding(10f);
                table.addCell(emptyCell);
            }

            document.add(table);

            // ---------- FOOTER ----------
            Paragraph footer = new Paragraph(
                    "Generated by Alh Isah Kato Farms © " + LocalDate.now(),
                    footerFont
            );
            footer.setAlignment(Element.ALIGN_CENTER);
            footer.setSpacingBefore(10);
            document.add(footer);

        } catch (Exception e) {
            System.err.println("❌ PDF generation failed: " + e.getMessage());
            e.printStackTrace();
            throw e;
        } finally {
            if (document != null && document.isOpen()) {
                document.close();
            }
        }

        return out.toByteArray();
    }


    private static Field[] getAllFields(Class<?> type) {
        List<Field> fields = new ArrayList<>();
        for (Class<?> c = type; c != null && c != Object.class; c = c.getSuperclass()) {
            fields.addAll(List.of(c.getDeclaredFields()));
        }
        return fields.toArray(new Field[0]);
    }
}
